source 'https://rubygems.org'

ruby '> 2.1'
gem 'inflector'
gem 'gmail'
gem 'net-ping'
gem 'pg'
gem 'rack'
gem 'rack-contrib'
gem 'rubocop'
gem 'rufus-scheduler'
gem 'rx'
gem 'sequel'
gem 'sequel_pg', require: 'sequel'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-sequel'

group :test do
  gem 'rack-latency'
  gem 'rspec'
end
